owner = global.owner;
spriteName = "";
handSide = noone; // l | r | s | e | o
damages = ds_map_create();
isRanged = false;
nextChoices = [];
projectileSpeed = 0;
numberOfTargets = 1;
staggersAgainstBlocks = true;